### PR TITLE
ref: Remove paging + Gracefully handle orgs

### LINKED ISSUE #129: Handle partial 400 gracefully
We figured out the problem that Bruno had, for him this request `https://sentry.io/api/0/organizations/testorg-az/sessions/?project=-1&interval=90d&statsPeriod=90d&field=sum%28session%29&groupBy=project` is failing with a `400` because he is in a weird state with that org.

Can we make it that if one of those cascading requests of fetching session data for an org fails, we just skip it and show data of the ones that succeeded?

https://sentry.io/share/issue/97ac24cff3b146d88dc3349501052b0a/

### LINKED ISSUE #136: Scanning QR Code fails
After installing the APK, I tried to scan the QR from the [mobila-app](https://sentry.io/settings/account/api/mobile-app/).
It failed to scan and the page is now stuck on Sessions with the message "Error - Something went wrong. Please try again" and a "Retry" button. Nothing works.

If I press on the gear, I can then sign out.
I also tried to paste the token but it also fails.

### LINKED ISSUE #140: Remain Calm Screen - No pull to refresh
Can't pull to refresh when on "Remain Calm Screen"

### PR DESCRIPTION
**Pull request by HazAT**
Add Loading State

https://user-images.githubusercontent.com/363802/109237366-b09ecf00-77d1-11eb-9ed4-4be80b12fc43.mov

Fixes #140
Fixes #129
Fixes #136 I think

### CODE REVIEW

File: lib/redux/middleware/sentry_api_middleware.dart [hunk 1]
```diff
@@ -15,49 +15,40 @@ class SentryApiMiddleware extends MiddlewareClass<AppState> {
...
-                projectCursorsByOrganizationSlug[organization.slug] = currentCursor;
-              } else {
-                projectCursorsByOrganizationSlug[organization.slug] = nextCursor;
-              }
+            store.dispatch(LoadingAction(true, '${organization.name} -> Checking for sessions...'));
+            try {
+              final projectsWithSessionsForOrganization = await api.projectIdsWithSessions(organization.slug);
+              projectIdsWithSessions.addAll(projectsWithSessionsForOrganization);
+            } catch (_) {
+              // We skip this org since it has no projects
```
Comment (bruno-garcia) [inline lib/redux/middleware/sentry_api_middleware.dart:43]: What about a breadcrumb?

**Review by bruno-garcia — COMMENTED** [review]
Very cool

File: lib/redux/middleware/sentry_api_middleware.dart (hunk 1 above)
Comment (HazAT) [reply lib/redux/middleware/sentry_api_middleware.dart:43]: there u go

File: lib/api/sentry_api.dart [hunk 2]
```diff
@@ -41,13 +41,8 @@ class SentryApi {
...
 
-  Future<List<Project>> projects(String slug, Cursor cursor) async {
-    final queryParameters = <String, String>{
-    };
-
-    if (cursor != null) {
-      queryParameters[cursor.queryKey()] = cursor.queryValue();
-    }
+  Future<List<Project>> projects(String slug) async {
+    final queryParameters = <String, String>{};
```
Comment (denrase) [inline lib/api/sentry_api.dart:44]: We should remove `queryParameters`, as it is not used anymore.

File: lib/redux/middleware/sentry_api_middleware.dart [hunk 3]
```diff
@@ -15,49 +16,43 @@ class SentryApiMiddleware extends MiddlewareClass<AppState> {
   @override
   dynamic call(Store<AppState> store, action, next) {
     if (action is FetchOrganizationsAndProjectsAction) {
+      store.dispatch(LoadingAction(true));
```
Comment (denrase) [inline lib/redux/middleware/sentry_api_middleware.dart:18]: We should rename `LoadingAction` to something like `OrgsAndProjectsLoadingAction`

File: lib/redux/middleware/sentry_api_middleware.dart [hunk 4]
```diff
@@ -15,49 +16,43 @@ class SentryApiMiddleware extends MiddlewareClass<AppState> {
...
+              Sentry.addBreadcrumb(Breadcrumb(message: 'Org has no projects -> $e', level: SentryLevel.error));
             }
           }
-          store.dispatch(FetchOrganizationsAndProjectsSuccessAction(individualOrganizations, projectsByOrganizationId, projectCursorsByOrganizationSlug, projectIdsWithSessions, action.reload));
+          store.dispatch(LoadingAction(true, 'Almost there'));
+          store.dispatch(FetchOrganizationsAndProjectsSuccessAction(individualOrganizations, projectsByOrganizationId, projectIdsWithSessions));
         } catch (e, s) {
           store.dispatch(FetchOrganizationsAndProjectsFailureAction(e, s));
         }
+        store.dispatch(LoadingAction(false));
```
Comment (denrase) [inline lib/redux/middleware/sentry_api_middleware.dart:54]: Since loading action is specific for this screen, we could remove the boolean parameter and just provide the progress and text, since it is clear that we are loading between `FetchOrganizationsAndProjectsAction` and `FetchOrganizationsAndProjectsSuccessAction/FetchOrganizationsAndProjectsFailureAction `. This would remove some redundancy.

File: lib/redux/state/app_state.dart [hunk 5]
```diff
@@ -170,6 +176,9 @@ class GlobalState {
       apdexBeforeByProjectId: apdexBeforeByProjectId ?? this.apdexBeforeByProjectId,
       issuesByProjectSlug: issuesByProjectSlug ?? this.issuesByProjectSlug,
       selectedOrganization: selectedOrganization ?? this.selectedOrganization,
+      isLoading: isLoading ?? this.isLoading,
+      loadingText: loadingText ?? this.loadingText,
```
Comment (denrase) [inline lib/redux/state/app_state.dart:180]: Since `loadingText ` and `loadingProgress` are nullable, we can never reset then back to null once they have a value. They will always fallback to the current instance value. See `setTokenNull` for reference.

File: lib/redux/state/app_state.dart [hunk 6]
```diff
@@ -95,7 +98,9 @@ class GlobalState {
   final Map<String, String> organizationsSlugByProjectSlug;
   final Map<String, Cursor> projectCursorsByOrganizationSlug;
   final Map<String, List<Project>> projectsByOrganizationSlug;
-  final bool projectsFetchedOnce;
+  final bool isLoading;
```
Comment (denrase) [inline lib/redux/state/app_state.dart:101]: Maybe we can get some context in the app names, as they represent the state of orgs and projects loading.

File: lib/screens/health/health_screen.dart [hunk 7]
```diff
@@ -36,28 +35,34 @@ class _HealthScreenState extends State<HealthScreen> {
   }
 
   Widget _content(HealthScreenViewModel viewModel) {
-    if (viewModel.showProjectEmptyScreen) {
+    if (viewModel.showLoadingScreen) {
+      return Scaffold(body:
```
Comment (denrase) [inline lib/screens/health/health_screen.dart:39]: Do we need the `Scaffold` widget?

File: lib/screens/health/health_screen.dart [hunk 8]
```diff
@@ -36,28 +35,34 @@ class _HealthScreenState extends State<HealthScreen> {
...
+      Center(child:
+        Column(
+            mainAxisAlignment : MainAxisAlignment.center,
+            crossAxisAlignment : CrossAxisAlignment.center,
+            children: [
+              CircularProgressIndicator(value: viewModel.loadingProgress),
+              Container(
+                  padding: EdgeInsets.only(top: 16, left: 22, right: 22),
```
Comment (denrase) [inline lib/screens/health/health_screen.dart:47]: We can use `EdgeInsets.symetric(vertical: 16, horizontal: 22)` if we would also like to have some inset at the bottom.

File: lib/redux/state/app_state.dart [hunk 9]
```diff
@@ -95,7 +98,9 @@ class GlobalState {
   final Map<String, String> organizationsSlugByProjectSlug;
   final Map<String, Cursor> projectCursorsByOrganizationSlug;
```
Comment (denrase) [inline lib/redux/state/app_state.dart:99]: We should remove `projectCursorsByOrganizationSlug`

File: lib/redux/middleware/sentry_api_middleware.dart [hunk 10]
```diff
@@ -15,49 +16,43 @@ class SentryApiMiddleware extends MiddlewareClass<AppState> {
...
-                projectCursorsByOrganizationSlug[organization.slug] = currentCursor;
-              } else {
-                projectCursorsByOrganizationSlug[organization.slug] = nextCursor;
-              }
+            store.dispatch(LoadingAction(true, '${organization.name} -> Checking for sessions...', ++currentProgress / fullProgress));
+            try {
+              final projectsWithSessionsForOrganization = await api.projectIdsWithSessions(organization.slug);
+              projectIdsWithSessions.addAll(projectsWithSessionsForOrganization);
+            } catch (e) {
+              Sentry.addBreadcrumb(Breadcrumb(message: 'Org has no projects -> $e', level: SentryLevel.error));
```
Comment (denrase) [inline lib/redux/middleware/sentry_api_middleware.dart:46]: Maybe we should do a fallback here, and just show the projects we have instead of showing none? User will have projects without session data, but i think this might be better than showing none?

**Review by denrase — CHANGES_REQUESTED** [review]
- We can now remove the `Cursor` class and the generated code for it.
- For my taste the text is a bit too much, because i'm not able to read it because it goes by so fast for most steps.

File: lib/screens/health/health_screen.dart (hunk 7 above)
Comment (HazAT) [reply lib/screens/health/health_screen.dart:39]: I wasn't able to position it center otherwise with loading indicator and text 🙈

File: lib/redux/middleware/sentry_api_middleware.dart (hunk 10 above)
Comment (HazAT) [reply lib/redux/middleware/sentry_api_middleware.dart:46]: I think showing the empty screen that says, no projects with session data makes more sense. Otherwise, the logic is different here for no reason.

File: lib/redux/middleware/sentry_api_middleware.dart (hunk 4 above)
Comment (HazAT) [reply lib/redux/middleware/sentry_api_middleware.dart]: I would just keep the `boolean` so we don't need to deal with the "nullability" of text and progress. Only when the boolean is true we show the loading screen.

File: lib/redux/state/app_state.dart (hunk 5 above)
Comment (HazAT) [reply lib/redux/state/app_state.dart:174]: I would just keep the `boolean` so we don't need to deal with the "nullability" of text and progress. Only when the boolean is true we show the loading screen.

File: lib/redux/state/app_state.dart (hunk 6 above)
Comment (HazAT) [reply lib/redux/state/app_state.dart:97]: Sorry not sure what you mean here.

**Comment by HazAT** [comment]
> For my taste the text is a bit too much, because i'm not able to read it because it goes by so fast for most steps.

On slow connections or large orgs you have time to read it.

File: lib/redux/state/app_state.dart (hunk 6 above)
Comment (denrase) [reply lib/redux/state/app_state.dart:97]: `isLoading` -> `isLoadingOrgsAndProjects`, as `isLoading` is too general for the whole app state.

File: lib/screens/health/health_screen.dart (hunk 7 above)
Comment (denrase) [reply lib/screens/health/health_screen.dart:39]: Don't think we are supposed to use Scaffold in this place, i will give it a try.

File: lib/redux/middleware/sentry_api_middleware.dart (hunk 4 above)
Comment (denrase) [reply lib/redux/middleware/sentry_api_middleware.dart]: Could have written this better. 🤦  I meant that `FetchOrganizationsAndProjectsAction` and `FetchOrganizationsAndProjectsSuccessAction/FetchOrganizationsAndProjectsFailureAction` would set the boolean, as the represent the flow/lifecycle of the call. Either way works in the end, so we can also leave it in the loading action.

File: lib/redux/state/app_state.dart (hunk 5 above)
Comment (denrase) [reply lib/redux/state/app_state.dart:174]: We should still set the correct state when we are done, as we leave the old text and never reset it. Could become an issue if we need to show loading again where we just set the boolean, then we would show old text. Better to do the correct thing in the reducer.

Comment (denrase) [reply lib/redux/state/app_state.dart:174]: We can reset the values if loading is false for example. `loadingText: !isLoading ? null : loadingText ?? this.loadingText,`

File: lib/screens/health/health_screen.dart (hunk 7 above)
Comment (denrase) [reply lib/screens/health/health_screen.dart]: Works without it and we also have white as background color as in other states.

**Review by denrase — APPROVED** [review]
