### PR TITLE
Fix code generation

### LINKED ISSUE #199: Code generation is broken: `Could not generate `toJson` code for `stats24h` because of type `Stat`.`
```
➜  sentry-mobile git:(main) flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 373ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 81ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 433ms

[INFO] Running build...
[INFO] Running build completed, took 21ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 51ms

[SEVERE] json_serializable:json_serializable on lib/types/stats.dart (cached):

Could not generate `toJson` code for `stats24h` because of type `Stat`.
package:sentry_mobile/types/stats.dart:14:21
   ╷
14 │   final List<Stat>? stats24h;
   │                     ^^^^^^^^
   ╵
```

### PR DESCRIPTION
**Pull request by denrase**
# Overview 

- Provide to/from json functions for `Stats` properties.
- Remove generated files form version control.
- Generate files on CI.

Closes #199

### CODE REVIEW

**Comment by denrase** [comment]
@ueman Not sure about excluding the generated files. How would we guarantee that users re-generate if files locally are stale but would still compile without issue and we'd get runtime issues? This is easier for dependencies like `pods`, as we always have the `lock` file which guarantees re-generation.

**Comment by ueman** [comment]
I do not have a good answer to that, except for documenting it in the readme.
You should use build_runner with the [watch option](https://dart.dev/tools/build_runner), so that you aren't running into stale files locally. You can add a launch option for it in Android Studio or VS Code.

File: lib/types/stats.dart [hunk 1]
```diff
@@ -8,10 +8,10 @@ class Stats {
   Stats(this.stats24h, this.stats14d);
   factory Stats.fromJson(Map<String, dynamic> json) => _$StatsFromJson(json);
 
-  @JsonKey(name: '24h')
+  @JsonKey(name: '24h', fromJson: Stat.fromJsonList, toJson: Stat.toJsonList)
   final List<Stat>? stats24h;
```
Comment (ueman) [inline lib/types/stats.dart:12]: Shouldn't the `Stat`class have a `@JsonSerializable` attribute? 
If that's present, you won't need to add the methods manually like you did, and it should just work

Comment (ueman) [reply lib/types/stats.dart:12]: Ah I see, it corresponds to an array and not to an object, nevermind then.

Comment (denrase) [reply lib/types/stats.dart:12]: Yeah, it's because we have this array of arrays that we have custom serialization.

**Comment by denrase** [comment]
@ueman Decided to go with your suggestion after all. 😅

File: .gitignore [hunk 2]
```diff
@@ -31,6 +31,9 @@
 .pub/
 /build/
 
+# Generated
+lib/types/*.g.dart
```
Comment (ueman) [inline .gitignore:35]: This could be just 
```suggestion
*.g.dart
```

File: README.md [hunk 3]
```diff
@@ -35,7 +35,15 @@ flutter pub get
 
 https://flutter.dev/docs/get-started/editor
 
-5. Run the App
+5. Generate Transient Files
+
+Files used for JSON decoding are generated using [`build_runner`](https://dart.dev/tools/build_runner).
+
+```
+flutter pub run build_runner build
```
Comment (ueman) [inline README.md:43]: Maybe add a note for the watch option and how to delete conflicting files?

- https://pub.dev/packages/build_runner#built-in-commands
- https://pub.dev/packages/build_runner#command-line-options

File: .github/workflows/build.yml [hunk 4]
```diff
@@ -28,6 +28,10 @@ jobs:
         - name: Fix iOS build bug
           if: matrix.target == 'ios'
           run: rm ios/Podfile
+        - name: Pub Get & Build Runner
+          run: |
+            flutter pub get
+            flutter pub run build_runner build
```
Comment (ueman) [inline .github/workflows/build.yml:34]:
```suggestion
            flutter pub run build_runner build --delete-conflicting-files
```

In case, someone did commit auto-generated files?

**Comment by ueman** [comment]
Other than the couple nitpicks, this LGTM.

File: .github/workflows/build.yml (hunk 4 above)
Comment (denrase) [reply .github/workflows/build.yml:34]: I'd rather have the CI build fail in this case so we know we have to fix it. WDYT?

Comment (ueman) [reply .github/workflows/build.yml:34]: I don't have any strong preference. If it doesn't work like we expected, we can still change it later 👍
