### PR TITLE
Fix: Interval in sessions call

### LINKED ISSUE #164: The interval has to be less than one day.
Request: `https://sentry.io/api/0/organizations/sentry-sdks/sessions/?project=-1&interval=90d&statsPeriod=90d&field=sum%28session%29&groupBy=project`

`Org has no projects -> api error statusCode: 400 message: "{\"detail\":\"The interval has to be less than one day.\"}"`

https://sentry.io/organizations/sentry/issues/2269354795/?project=5645511&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3Ame_or_none

ref: https://github.com/getsentry/sentry/pull/24264

`interval=90d`
needs to be changed to `interval=1d`

### LINKED ISSUE #166: Have more robust error handling on API errors (response malforms)
So something like does won't happen anymore
https://github.com/getsentry/sentry-mobile/issues/136#issuecomment-797647908

### PR DESCRIPTION
**Pull request by denrase**
# Overview

- Use `1d` as interval in sessions call instead of `90d`
- Use correct data structure for empty screen

Closes #164
Closes #166

### CODE REVIEW

File: lib/api/sentry_api.dart [hunk 1]
```diff
@@ -57,7 +57,7 @@ class SentryApi {
   Future<Set<String>>projectIdsWithSessions(String organizationSlug) async {
     final queryParameters = <String, dynamic>{ /*String|Iterable<String>*/
       'project': '-1',
-      'interval': '90d',
+      'interval': '1d',
```
Comment (matejminar) [inline lib/api/sentry_api.dart:60]: @denrase Do you need to do some reducing on the client-side as now you won't get one bucket from the backend but rather 90?

Comment (denrase) [reply lib/api/sentry_api.dart:60]: I don't think we need to do anything else, as we are only interested in the project ids from this call and not the interval data.

Comment (matejminar) [reply lib/api/sentry_api.dart:60]: ah, cool 👍
